version: 0.0
os: linux
files:
  - source: /events
    destination: /var/www/html/events
  - source: /chinese
    destination: /var/www/html/chinese
  - source: /rbc
    destination: /var/www/html/rbc
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  